-- Digital Aastraa focused upgrade: rich editor, author profiles, recommendations and enquiry funnel.
-- Run this complete file once in Supabase Dashboard > SQL Editor.
-- It is idempotent and preserves existing users, posts, media and enquiries.
-- After this migration, run security_hardening.sql to switch public forms to the
-- validated, rate-limited submit_contact function.

alter table public.blog_posts
    add column if not exists recommended_post_ids uuid[] not null default '{}';
alter table public.blog_posts
    add column if not exists recommendation_position text not null default 'bottom';
alter table public.blog_posts add column if not exists author_role text;
alter table public.blog_posts add column if not exists author_bio text;
alter table public.blog_posts add column if not exists author_avatar_url text;
alter table public.blog_posts add column if not exists author_avatar_path text;

alter table public.blog_posts drop constraint if exists blog_posts_recommendation_position_check;
alter table public.blog_posts
    add constraint blog_posts_recommendation_position_check
    check (recommendation_position in ('bottom', 'sidebar'));

alter table public.blog_posts drop constraint if exists blog_posts_recommended_count_check;
alter table public.blog_posts
    add constraint blog_posts_recommended_count_check
    check (cardinality(recommended_post_ids) <= 3);

alter table public.blog_assets add column if not exists mime_type text;
alter table public.blog_assets add column if not exists size_bytes bigint not null default 0;
alter table public.blog_assets add column if not exists original_name text;
alter table public.blog_assets drop constraint if exists blog_assets_asset_type_check;
alter table public.blog_assets
    add constraint blog_assets_asset_type_check
    check (asset_type in ('cover', 'inline', 'author', 'video'));

alter table public.contact_submissions add column if not exists lead_source text not null default 'Website';
alter table public.contact_submissions add column if not exists enquiry_type text not null default 'contact';
alter table public.contact_submissions add column if not exists utm_source text;
alter table public.contact_submissions add column if not exists utm_medium text;
alter table public.contact_submissions add column if not exists utm_campaign text;
alter table public.contact_submissions add column if not exists landing_page text;
alter table public.contact_submissions add column if not exists referrer text;
alter table public.contact_submissions add column if not exists next_follow_up_at timestamptz;
alter table public.contact_submissions add column if not exists estimated_value numeric(12,2) not null default 0;
alter table public.contact_submissions add column if not exists stage_updated_at timestamptz not null default now();

alter table public.contact_submissions drop constraint if exists contact_submissions_enquiry_type_check;
alter table public.contact_submissions
    add constraint contact_submissions_enquiry_type_check
    check (enquiry_type in ('contact', 'audit'));

alter table public.contact_submissions drop constraint if exists contact_submissions_status_check;
update public.contact_submissions set status = 'lost' where status = 'closed';
alter table public.contact_submissions
    add constraint contact_submissions_status_check
    check (status in ('new', 'contacted', 'qualified', 'proposal', 'won', 'lost'));

alter table public.contact_submissions drop constraint if exists contact_submissions_estimated_value_check;
alter table public.contact_submissions
    add constraint contact_submissions_estimated_value_check
    check (estimated_value >= 0);

create table if not exists public.enquiry_stage_history (
    id bigint generated by default as identity primary key,
    submission_id uuid not null references public.contact_submissions(id) on delete cascade,
    from_status text,
    to_status text not null,
    changed_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create index if not exists contact_submissions_follow_up_idx
    on public.contact_submissions (next_follow_up_at)
    where next_follow_up_at is not null;
create index if not exists enquiry_stage_history_submission_idx
    on public.enquiry_stage_history (submission_id, created_at desc);

create or replace function public.stamp_enquiry_stage()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    if new.status is distinct from old.status then
        new.stage_updated_at = now();
    end if;
    return new;
end;
$$;

drop trigger if exists contact_submissions_stamp_stage on public.contact_submissions;
create trigger contact_submissions_stamp_stage
before update of status on public.contact_submissions
for each row execute function public.stamp_enquiry_stage();

create or replace function public.track_enquiry_stage()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if tg_op = 'INSERT' or new.status is distinct from old.status then
        insert into public.enquiry_stage_history (submission_id, from_status, to_status, changed_by)
        values (new.id, case when tg_op = 'UPDATE' then old.status else null end, new.status, auth.uid());
    end if;
    return new;
end;
$$;

drop trigger if exists contact_submissions_track_stage on public.contact_submissions;
create trigger contact_submissions_track_stage
after insert or update of status on public.contact_submissions
for each row execute function public.track_enquiry_stage();

alter table public.enquiry_stage_history enable row level security;
revoke all on table public.enquiry_stage_history from anon, authenticated;
grant select on table public.enquiry_stage_history to authenticated;

drop policy if exists "Admins can read enquiry history" on public.enquiry_stage_history;
create policy "Admins can read enquiry history"
on public.enquiry_stage_history for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "Visitors can submit contact forms" on public.contact_submissions;
create policy "Visitors can submit contact forms"
on public.contact_submissions for insert
to anon, authenticated
with check (
    char_length(trim(name)) between 2 and 120
    and char_length(trim(phone)) between 7 and 24
    and char_length(trim(email)) between 5 and 254
    and char_length(trim(service)) between 2 and 80
    and char_length(project_description) <= 5000
    and char_length(lead_source) between 1 and 120
    and char_length(coalesce(utm_source, '')) <= 160
    and char_length(coalesce(utm_medium, '')) <= 160
    and char_length(coalesce(utm_campaign, '')) <= 240
    and char_length(coalesce(landing_page, '')) <= 1000
    and char_length(coalesce(referrer, '')) <= 1000
    and status = 'new'
    and admin_notes = ''
    and estimated_value = 0
    and next_follow_up_at is null
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'blog-images',
    'blog-images',
    true,
    52428800,
    array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm', 'video/ogg']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.get_admin_resource_usage()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    result jsonb;
begin
    if not public.is_admin() then
        raise exception 'Not authorized';
    end if;

    select jsonb_build_object(
        'database_bytes', pg_database_size(current_database()),
        'database_limit_bytes', 524288000,
        'storage_bytes', coalesce((
            select sum(
                case
                    when objects.metadata ->> 'size' ~ '^[0-9]+$'
                    then (objects.metadata ->> 'size')::bigint
                    else 0
                end
            )
            from storage.objects as objects
            where objects.bucket_id = 'blog-images'
        ), 0),
        'storage_limit_bytes', 1073741824,
        'media_count', (select count(*) from public.blog_assets),
        'image_count', (select count(*) from public.blog_assets where asset_type <> 'video'),
        'video_count', (select count(*) from public.blog_assets where asset_type = 'video'),
        'media_tracked_bytes', (select coalesce(sum(size_bytes), 0) from public.blog_assets),
        'post_count', (select count(*) from public.blog_posts),
        'published_count', (select count(*) from public.blog_posts where status = 'published'),
        'draft_count', (select count(*) from public.blog_posts where status = 'draft'),
        'trash_count', (select count(*) from public.blog_posts where status = 'trashed'),
        'enquiry_count', (select count(*) from public.contact_submissions),
        'open_enquiry_count', (select count(*) from public.contact_submissions where status not in ('won', 'lost')),
        'won_enquiry_count', (select count(*) from public.contact_submissions where status = 'won'),
        'admin_count', (select count(*) from public.admin_users)
    ) into result;

    return result;
end;
$$;

revoke all on function public.get_admin_resource_usage() from public;
grant execute on function public.get_admin_resource_usage() to authenticated;

-- Refresh the Supabase REST schema cache so the new columns work immediately.
notify pgrst, 'reload schema';
